### PR TITLE
Update register.php

### PR DESCRIPTION
**Pull request by asher-lab**
Using XAMPP not removing "ssss" will return an error, else removing it will solve the problem.

### CODE REVIEW

**Comment by markszabo** [comment]
Hi @asher-lab 

Thanks for the contribution! This is an interesting bug, as according to the php doc: https://www.php.net/manual/en/mysqli-stmt.bind-param.php `ssss` is required here. Also the same function is used at other places: https://github.com/markszabo/PostQ/search?q=bind_param

Can you share the error you got with the `sssss` in place?

**Comment by asher-lab** [comment]
Hello there markszabo, here is the error when I include "ssss" on line 69 of register.php

```
Notice: Only variables should be passed by reference in C:\xampp\htdocs\PostQ-master1\PostQ-master\register.php on line 69
```
AND
```
Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in C:\xampp\htdocs\PostQ-master1\PostQ-master\register.php on line 69
Error during the execution of the SQL query
```

Image link: [https://prnt.sc/vy4idk](url)

**Comment by markszabo** [comment]
Hm, it seems that the notice comes from using a function call directly as a parameter to bind_param: https://stackoverflow.com/a/4636183/8590802

Can you try assigning the return values to variables and passing those to the bind_param call? Something like

```
$username = $_POST['username'];
$password = password_hash($_POST['password'], PASSWORD_BCRYPT);
$privatekey = $_POST['privatekey'];
$publickey = base64_decode($_POST['publickey']);

$stmt->bind_param("ssss", $username, $password, $privatekey, $publickey);
```

**Comment by asher-lab** [comment]
Thanks! I could just resort to removing ssss since it does work on my part and I find it working normal. I'll just close this pull request, thank you for your time. This is amazing, I find an inspiration to create one of these very soon!

**Comment by markszabo** [comment]
Sure, awesome, thanks again for taking the time to send the PR

**Pull request closed without merging**
